repos:

  - hooks:
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: requirements-txt-fixer
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: trailing-whitespace
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0

  - hooks:
      - additional_dependencies:
          - mdformat-toc
          - mdformat-tables
        args:
          - --wrap=80
        exclude: README_TF\.md
        id: mdformat
    repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16

  - hooks:
      - args:
          - -c=.yamllint-config.yaml
        id: yamllint
    repo: https://github.com/adrienverge/yamllint.git
    rev: v1.28.0

  - hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
        id: terraform_tflint
    repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.0

  - hooks:
      - entry: bash -c 'find . -name "*.yaml" -exec python3 -m pyaml -r {} \;; find
          . -name "*.yml" -exec python3 -m pyaml -r {} \;'
        id: yaml_format
        language: system
        name: Run yaml format
    repo: local

  - hooks:
      - args:
          - --baseline
          - .secrets.baseline
        id: detect-secrets
    repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0

  - hooks:
      - args:
          - --exclude=SC1090,SC1091,SC2154
        files: \.sh$
        id: shellcheck
    repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.2

  - hooks:
      - args:
          - -l
          - -w
        files: \.sh$
        id: shfmt
    repo: https://github.com/cisagov/pre-commit-shfmt
    rev: v0.0.2
